language: php
php:
  # see http://php.net/supported-versions.php
  - '5.6'
  - '7.0' # Until 3 Dec 2018
  - '7.1' # Until 1 Dec 2019
  - '7.2' # Until 30 Nov 2020
  - '7.3' # RC

services:
  - mysql

env:
  matrix:
    # see https://codex.wordpress.org/WordPress_Versions
    - WP_VERSION=4.0
    - WP_VERSION=4.9
    - WP_VERSION=nightly

before_install:
  - mysql -e 'CREATE DATABASE dev;'

install:
  - composer update
  # Using WP-CLI instead of Composer because this way we can use the env matrix (above).
  - vendor/bin/wp --allow-root core download --version=$WP_VERSION --force
  - vendor/bin/wp --allow-root config create --force --dbuser=travis --dbpass="" --dbhost="127.0.0.1"
  - vendor/bin/wp --allow-root core install
  # We get the latest patch version here to have less maintenance on the env matrix above.
  - vendor/bin/wp --allow-root core update --minor

script:
  - composer validate --strict --no-check-lock
  - vendor/bin/phpunit

matrix:
  allow_failures:
  - php: '5.6'
  - php: '7.1'
  - php: '7.2'
  - php: '7.3'
  - env: WP_VERSION=nightly