language: php

php:
  # see http://php.net/supported-versions.php
  # '7.0' # Until 3 Dec 2018
  - '7.1' # Until 1 Dec 2019
  - '7.2' # Until 30 Nov 2020
  - '7.3' # RC

env:
  global:
    - PHPUNIT_VERSION=~7
  matrix:
    # see https://phpunit.de/supported-versions.html
    # We check all of them because it once broke from one minor to another.
    - WP_VERSION=5.0 PHPUNIT_VERSION=6.5.*
    - WP_VERSION=5.0 PHPUNIT_VERSION=7.1.*
    - WP_VERSION=5.0 PHPUNIT_VERSION=7.2.*
    - WP_VERSION=5.0 PHPUNIT_VERSION=7.3.*
    - WP_VERSION=5.0 PHPUNIT_VERSION=7.4.*
    - WP_VERSION=5.0 PHPUNIT_VERSION=7.5.*
    # see https://codex.wordpress.org/WordPress_Versions
    # We check some versions because WP does not follow SemVer.
    - WP_VERSION=4.0
    - WP_VERSION=4.2
    - WP_VERSION=4.4
    - WP_VERSION=4.6
    - WP_VERSION=4.8
    - WP_VERSION=5.0

matrix:
  fast_finish: true
  include:
  # Still supported edges
  - php: '7.0'
    env: WP_VERSION=4.0 PHPUNIT_VERSION=6.5.*
  - php: '7.0'
    env: WP_VERSION=5.0 PHPUNIT_VERSION=6.5.*
  # Far-seeing test of bleeding edge
  - php: '7.3'
    env: WP_VERSION=nightly
  - php: hhvm
    env: WP_VERSION=5.0
  - php: nightly
    env: WP_VERSION=5.0
  # Introducing upcoming support
  - php: '5.6'
    env: PHPUNIT_VERSION=~5 WP_VERSION=4.9
  allow_failures:
  - php: '5.6'
  - php: hhvm
  - php: nightly
  - env: WP_VERSION=nightly
  - env: PHPUNIT_VERSION=~7 WP_VERSION=4.9
  - env: PHPUNIT_VERSION="7.2.*"
  - env: PHPUNIT_VERSION="7.4.*"
  - env: PHPUNIT_VERSION="7.5.*"

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE dev;'
  # Try supporting other versions
  - composer require --update-with-dependencies phpunit/phpunit:$PHPUNIT_VERSION

install:
  - composer update
  # Using WP-CLI instead of Composer because this way we can use the env matrix (above).
  - vendor/bin/wp --allow-root core download --version=$WP_VERSION --force
  - vendor/bin/wp --allow-root config create --force --dbuser=travis --dbpass="" --dbhost="127.0.0.1"
  - vendor/bin/wp --allow-root core install --skip-email
  # We get the latest patch version here to have less maintenance on the env matrix above.
  - vendor/bin/wp --allow-root core update --minor

script:
  - composer validate --strict --no-check-lock
  - vendor/bin/phpunit

after_failure:
  - cat srv/wp-content/debug.log || true