language: php
php:
  - '7.0'

services:
  - mysql

env:
  matrix:
    - WP_VERSION=4.0

before_install:
  - mysql -e 'CREATE DATABASE dev;'

install:
  - composer update
  - vendor/bin/wp --allow-root core download --version=$WP_VERSION --force
  - vendor/bin/wp --allow-root config create --force --dbuser=travis --dbpass=""
  - vendor/bin/wp --allow-root core install

script:
  - composer validate --strict --no-check-lock
  - vendor/bin/phpunit

matrix:
  allow_failures:
  - php: '7.0'