language: php

php:
  # see http://php.net/supported-versions.php
  - '7.0' # Until 3 Dec 2018
  - '7.1' # Until 1 Dec 2019
  - '7.2' # Until 30 Nov 2020
  - '7.3' # Until 6 Dec 2021
  - '7.4' # Until 28 Nov 2022

env:
  global:
    - PHPUNIT_VERSION=6.5.*
  matrix:
    # see https://codex.wordpress.org/WordPress_Versions
    # see https://phpunit.de/supported-versions.html
    - WP_VERSION=5.4
    - WP_VERSION=nightly

matrix:
  # in the process to achieve support
  allow_failures:
  - php: '5.6'
  - env: WP_VERSION=nightly
  include:
  # see https://codex.wordpress.org/WordPress_Versions
  # see https://phpunit.de/upported-versions.html
  - php: '7.3'
    env: PHPUNIT_VERSION="7.5.*" WP_VERSION=5.2
  - php: '7.2'
    env: PHPUNIT_VERSION="7.0.*" WP_VERSION=5.0

  - php: '7.1'
    env: PHPUNIT_VERSION="6.5.*" WP_VERSION=4.8
  - php: '7.0'
    env: PHPUNIT_VERSION="6.5.*" WP_VERSION=4.6

  # Trying to support ...
  - php: '5.6'
    env: PHPUNIT_VERSION=~5 WP_VERSION=4.9


services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE dev;'
  # Try supporting other versions
  - composer require --update-with-dependencies phpunit/phpunit:$PHPUNIT_VERSION

install:
  - composer update
  # Using WP-CLI instead of Composer because this way we can use the env matrix (above).
  - vendor/bin/wp --allow-root core download --version=$WP_VERSION --force
  - vendor/bin/wp --allow-root config create --force --dbuser=travis --dbpass="" --dbhost="127.0.0.1"
  - vendor/bin/wp --allow-root core install --skip-email
  # We get the latest patch version here to have less maintenance on the env matrix above.
  - vendor/bin/wp --allow-root core update --minor

script:
  - composer validate --strict --no-check-lock
  - vendor/bin/phpunit
  # Run the code style test only in one PHP version to spare CI runtime
  - "[[ $TRAVIS_PHP_VERSION != 7.3 ]] || composer pre-commit"

after_failure:
  - cat srv/wp-content/debug.log || true

cache:
  directories:
    - $HOME/.composer/cache/files