version: '3'

services:
  php:
    image: pretzlaw/php:7.0-apache
    volumes:
      - ".:/var/www"
      - "$COMPOSER_CACHE_DIR:/var/composer"
    environment:
      COMPOSER_CACHE_DIR: /var/composer
      HTTPD__DocumentRoot: /var/www/srv
      HTTPD_a2enmod: rewrite
      PHP__memory_limit: 512M
      PHP__session.save_path: /var/www/var/sessions
      PHP_php5enmod: mysqli xdebug zip
      XDEBUG_CONFIG: remote_host=10.213.37.1 idekey=PHPSTORM remote_connect_back=1 remote_enable=1 profiler_enable_trigger=1
      PHP_IDE_CONFIG: "serverName=php"
    networks:
      default:
        ipv4_address: 10.213.37.3
  db:
    image: mysql:5.7
    volumes:
      - ".docker/db:/var/lib/mysql"
    environment:
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
      MYSQL_DATABASE: dev
      MYSQL_ROOT_PASSWORD: dev
    networks:
      default:
        ipv4_address: 10.213.37.4

networks:
  default:
    ipam:
      config:
        - subnet: 10.213.37.0/24
